# Generated by Django 4.0.2 on 2022-02-15 11:00

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextResource',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text_type', models.CharField(max_length=30)),
                ('text_profile', models.URLField(blank=True, null=True)),
                ('text_format', models.CharField(max_length=255)),
                ('label', models.JSONField(blank=True, null=True)),
                ('text_title', models.JSONField(blank=True, null=True)),
                ('text_subtitle', models.JSONField(blank=True, null=True)),
                ('text_content', models.TextField(blank=True, null=True)),
                ('selector', models.JSONField(blank=True, null=True)),
                ('language_iso639_2', models.CharField(blank=True, max_length=3, null=True)),
                ('language_iso639_1', models.CharField(blank=True, max_length=2, null=True)),
                ('language_display', models.CharField(blank=True, max_length=64, null=True)),
                ('language_pg', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='textresource',
            index=models.Index(fields=['text_type'], name='text_store__text_ty_b3e80b_idx'),
        ),
        migrations.AddIndex(
            model_name='textresource',
            index=models.Index(fields=['text_profile'], name='text_store__text_pr_667afd_idx'),
        ),
        migrations.AddIndex(
            model_name='textresource',
            index=models.Index(fields=['text_format'], name='text_store__text_fo_7a280f_idx'),
        ),
        migrations.AddIndex(
            model_name='textresource',
            index=models.Index(fields=['text_title'], name='text_store__text_ti_e6a10c_idx'),
        ),
        migrations.AddIndex(
            model_name='textresource',
            index=models.Index(fields=['text_subtitle'], name='text_store__text_su_849ca6_idx'),
        ),
        migrations.AddIndex(
            model_name='textresource',
            index=models.Index(fields=['label'], name='text_store__label_bb3af9_idx'),
        ),
        migrations.AddIndex(
            model_name='textresource',
            index=models.Index(fields=['language_iso639_2', 'language_iso639_1', 'language_display'], name='text_store__languag_44bff3_idx'),
        ),
    ]
